name: Cypress E2E tests
on: [push]
jobs:
  Cypress-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: clone server repo
        uses: actions/checkout@v3
        with:
          repository: 'winstonco/sham-illustrator-server'
          path: 'sham-illustrator-server'

      - name: build and start server
        run: |
          cd sham-illustrator-server
          npm run build
          npm install forever
          npx forever dist/server.js
        env:
          PORT: 5555
          ORIGIN: '*'
          OUT_OF_GAME_DRAW_ENABLED: true
          TURN_LENGTH: 3
          CLEAR_ON_END: true
          TIME_TO_GUESS: 10
          MINIMUM_PLAYERS: 3
          TRACE_LEVEL: 2

      - name: checkout client
        uses: actions/checkout@v3

      - name: cypress tests
        uses: cypress-io/github-action@v5
        with:
          install: npm ci
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
          browser: chrome
          spec: |
            cypress/e2e/**.cy.ts
        env:
          VITE_SERVER_URL: 'http://localhost:5555'
          VITE_CHANGELOG_URL: '/changelog'
          PORT: 3000
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
